name: blogenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flake8
  - pip
  - pip:
      - asgiref==3.8.1
      - blinker==1.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - Django==5.2
      - djangorestframework==3.16.0
      - Flask==3.1.0
      - gunicorn==23.0.0
      - whitenoise
      - idna==3.10
      - itsdangerous==2.2.0
      - Jinja2==3.1.6
      - MarkupSafe==3.0.2
      - packaging==25.0
      - requests==2.32.3
      - sqlparse==0.5.3
      - tzdata==2025.2
      - urllib3==2.4.0
      - Werkzeug==3.1.3
